/* Generated By:JavaCC: Do not edit this line. AFCOMPOSERConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AFCOMPOSERConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int KWDEBUT = 5;
  /** RegularExpression Id. */
  int KWINTERFACE = 6;
  /** RegularExpression Id. */
  int KWCOMP = 7;
  /** RegularExpression Id. */
  int KWPROP = 8;
  /** RegularExpression Id. */
  int KWEVT = 9;
  /** RegularExpression Id. */
  int KWINIT = 10;
  /** RegularExpression Id. */
  int KWACTIONS = 11;
  /** RegularExpression Id. */
  int KWFIN = 12;
  /** RegularExpression Id. */
  int KWIF = 13;
  /** RegularExpression Id. */
  int KWTHEN = 14;
  /** RegularExpression Id. */
  int KWPV = 15;
  /** RegularExpression Id. */
  int ALTERNATIVE = 16;
  /** RegularExpression Id. */
  int CHOIX = 17;
  /** RegularExpression Id. */
  int KWTWOP = 18;
  /** RegularExpression Id. */
  int TYPE = 19;
  /** RegularExpression Id. */
  int PROPTYPE = 20;
  /** RegularExpression Id. */
  int EVENT = 21;
  /** RegularExpression Id. */
  int ID = 22;
  /** RegularExpression Id. */
  int OP = 23;
  /** RegularExpression Id. */
  int COND = 24;
  /** RegularExpression Id. */
  int AFFECT = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"DEBUT\"",
    "\"INTERFACE\"",
    "\"COMP\"",
    "\"PROP\"",
    "\"EVT\"",
    "\"INITIALISATIONS\"",
    "\"ACTIONS\"",
    "\"FIN\"",
    "<KWIF>",
    "<KWTHEN>",
    "\";\"",
    "\"+\"",
    "\"~\"",
    "\":\"",
    "<TYPE>",
    "<PROPTYPE>",
    "<EVENT>",
    "<ID>",
    "<OP>",
    "<COND>",
    "<AFFECT>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"::\"",
    "\":=\"",
  };

}
