/* Generated By:JavaCC: Do not edit this line. Simple1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Simple1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int KWDEBUT = 5;
  /** RegularExpression Id. */
  int KWINTER = 6;
  /** RegularExpression Id. */
  int KWCOMP = 7;
  /** RegularExpression Id. */
  int KWINIT = 8;
  /** RegularExpression Id. */
  int KWACT = 9;
  /** RegularExpression Id. */
  int KWEVT = 10;
  /** RegularExpression Id. */
  int KWPROP = 11;
  /** RegularExpression Id. */
  int KWTWOP = 12;
  /** RegularExpression Id. */
  int KWPV = 13;
  /** RegularExpression Id. */
  int KWEQU = 14;
  /** RegularExpression Id. */
  int ALTERNATIVE = 15;
  /** RegularExpression Id. */
  int CHOIX = 16;
  /** RegularExpression Id. */
  int TYPE = 17;
  /** RegularExpression Id. */
  int PROPTYPE = 18;
  /** RegularExpression Id. */
  int ID = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"DEBUT\"",
    "\"INTERFACE\"",
    "\"COMP\"",
    "\"INITIALISATION\"",
    "\"ACTIONS\"",
    "\"EVT\"",
    "\"PROP\"",
    "\":\"",
    "\";\"",
    "\"=\"",
    "\"+\"",
    "\"$\"",
    "<TYPE>",
    "<PROPTYPE>",
    "<ID>",
    "\"{\"",
    "\",\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"a\"",
  };

}
